### ISSUE TITLE
Running fails with NameError: global name 'MultipleInvalid' is not defined

### ISSUE THREAD

**Issue by pdreker** [adfinis-sygroup/foreman-yml#52]
When using foreman-yml from foreman-ansible my runs fail with the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/foreman-yml", line 9, in 
    load_entry_point('foreman-yaml==0.0.2', 'console_scripts', 'foreman-yml')()
  File "/usr/local/lib/python2.7/dist-packages/foreman_yaml-0.0.2-py2.7.egg/foremanclient/foreman_yml.py", line 142, in main
    fm_import(fm_imp)
  File "/usr/local/lib/python2.7/dist-packages/foreman_yaml-0.0.2-py2.7.egg/foremanclient/foreman_yml.py", line 64, in fm_import
    fm.process_config_provisioningtpl()
  File "/usr/local/lib/python2.7/dist-packages/foreman_yaml-0.0.2-py2.7.egg/foremanclient/importer.py", line 330, in process_config_provisioningtpl
    except MultipleInvalid as e:
NameError: global name 'MultipleInvalid' is not defined
```
After adding `from voluptuous import MultipleInvalid` at the top of foreman-yml/foremanclient/importer.py the run succeeds.

**Comment by andreabettich** [comment]
Thanks for reporting an Issue.
I will try to reproduce it and report back to you.

**Comment by karras** [comment]
Project archived
